#!/bin/bash
[ -f .env ] || exit 1

set -a
. .env
set +a

helm upgrade --install data helm/Data \
    --namespace data \
    --create-namespace \
    --set global.postgresql.auth.username="$DB_USERNAME" \
    --set global.postgresql.auth.password="$DB_PASSWORD" \
    --set global.postgresql.auth.postgresPassword="$DB_SU_PASSWORD" \
    --set global.postgresql.auth.database="$DB_NAME"

if netstat -an | awk '$0 ~ /:5432([^0-9]|$)/' > /dev/null; then
  echo "Port 5432 (PostgreSQL is probably running, skipping)"
else
  kubectl port-forward svc/data-postgresql 5432:5432 &
fi

#if netstat -an | awk '$0 ~ /:5672([^0-9]|$)/' > /dev/null; then
#  echo "Port 5672 (RabbitMQ AMQP is probably running, skipping)"
#else
#  kubectl port-forward svc/data-postgresql 5432:5432 &
#fi