#!/bin/bash
[ -f .env ] || exit 1

set -a
. .env
set +a

helm upgrade --install data helm/Data \
    --namespace data \
    --create-namespace \
    --set global.postgresql.auth.username="$DB_USERNAME" \
    --set global.postgresql.auth.password="$DB_PASSWORD" \
    --set global.postgresql.auth.postgresPassword="$DB_SU_PASSWORD" \
    --set global.postgresql.auth.database="$DB_NAME" \
    --set redis.auth.password="$REDIS_PASSWORD"

helm upgrade --install communication helm/Communication \
    --namespace communication \
    --create-namespace \
    --set rabbitmq.auth.username="$RABBITMQ_USER" \
    --set rabbitmq.auth.password="$RABBITMQ_PASSWORD" \
    --set rabbitmq.auth.su_username="$RABBITMQ_SU_USER" \
    --set rabbitmq.auth.su_password="$RABBITMQ_SU_PASSWORD"

echo "To make cluster services work with local environment use 'telepresence connect --context=minikube' (if using minikube) command"