FROM eclipse-temurin:21.0.7_6-jdk-alpine-3.21

LABEL name="encryptify-core"
LABEL maintainer="Dayfit"
LABEL description="Encryptify Core Service"

COPY ./.mvn /app/.mvn
COPY ./mvnw /app/mvnw

COPY ./encryptify-core /app/encryptify-core
WORKDIR /app

# Compile source code
RUN \
    cd /app/encryptify-core && \
    ../mvnw package -DskipTests && \
    mv /app/encryptify-core/target/encryptify-core-*.jar /app/encryptify-core.jar

CMD ["java", "-jar", "/app/encryptify-core.jar"]

EXPOSE 8080