FROM eclipse-temurin:21.0.7_6-jdk-alpine-3.21

LABEL name="encryptify-encryption"
LABEL maintainer="Dayfit"
LABEL description="Encryptify Encryption Service"

COPY ./.mvn /app/.mvn
COPY ./mvnw /app/mvnw

COPY ./encryptify-encryption /app/encryptify-encryption
WORKDIR /app

# Compile source code
RUN \
    cd /app/encryptify-encryption && \
    ../mvnw package -DskipTests && \
    mv /app/encryptify-encryption/target/encryptify-encryption-*.jar /app/encryption.jar

CMD ["java", "-jar", "/app/encryption.jar"]

EXPOSE 8081