apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: data-configuration
  namespace: data
spec:
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
  project: infra
  source:
    chart: data
    repoURL: https://github.com/Day-fit/Encryptify-CD.git
    targetRevision: HEAD
    helm:
      releaseName: data
  destination:
    server: "https://kubernetes.default.svc"
    namespace: data