name: build-docker
on:
  release:
    types: [released]

permissions:
  contents: read
  packages: write

jobs:
  build-backend:
    name: Build Encryptify Microservices Images
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        service: [auth, encryption, core, email, stats]
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Maven
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<EOF
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
          http://maven.apache.org/xsd/settings-1.0.0.xsd">
          <servers>
          <server>
          <id>github</id>
          <username>${{ github.actor }}</username>
          <password>${{ secrets.GITHUB_TOKEN }}</password>
          </server>
          </servers>
          </settings>
          EOF

      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          file: ./dockerfiles/dockerfile-${{ matrix.service }}
          platforms: linux/amd64,linux/arm64/v8
          tags: ghcr.io/day-fit/encryptify-${{ matrix.service }}:latest,ghcr.io/day-fit/encryptify-${{ matrix.service }}:${{ github.event.release.tag_name }}
          secrets: |
            gh_name=${{ github.actor }}
            github_token=${{ secrets.GITHUB_TOKEN }}

  build-frontend:
    name: Build Encryptify Frontend Image
    runs-on: ubuntu-22.04
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v5.0.0

      - name: Download dependencies
        working-directory: encryptify-frontend
        run: |
          npm ci

      - name: Export to static files
        working-directory: encryptify-frontend
        run: |
          npx next build

      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          file: ./dockerfiles/dockerfile-frontend
          platforms: linux/amd64,linux/arm64/v8
          tags: ghcr.io/day-fit/encryptify-frontend:latest,ghcr.io/day-fit/encryptify-frontend:${{ github.event.release.tag_name }}