name: Upload rendered charts into CD repository
on:
  push:
    branches:
      - main

jobs:
  update-cd:
    runs-on: ubuntu-22.04
    environment:
      name: CD pipeline
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build helm dependencies
        run: | 
          cd helm/Data
          helm dependency build

      - name: Render CD files
        env:
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_SU_PASSWORD: ${{ secrets.DB_SU_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          mkdir -p rendered
          helm template data helm/Data \
            --set global.postgresql.auth.username=${DB_USERNAME} \
            --set global.postgresql.auth.password=${DB_PASSWORD} \
            --set global.postgresql.auth.postgresPassword=${DB_SU_PASSWORD} \
            --set global.postgresql.auth.database=${DB_NAME} > rendered/Data.yaml

      - name: Upload rendered files to CD repo
        env:
          CD_PAT: ${{ secrets.CD_PAT }}
          CD_REPO: ${{ secrets.CD_REPO }}
        run: |
          cd rendered
          git init
          git config user.name "CD Pipeline"
          git config user.email "cd_pipeline@dayfit.pl"
          git remote add origin https://x-access-token:${CD_PAT}@github.com/${CD_REPO}.git
          git add .
          git commit -m "Upload new CD configuration"
          git branch -M main
          git push -f origin main