name: Upload rendered charts into CD repository
on:
  push:
    branches:
      - main

jobs:
  update-cd:
    runs-on: ubuntu-22.04
    environment:
      name: CD pipeline
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build helm dependencies
        run: | 
          cd helm/Data
          helm dependency build

      - name: Render CD files
        env:
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_SU_PASSWORD: ${{ secrets.DB_SU_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          mkdir -p rendered
          helm template data helm/Data \
            --set global.postgresql.auth.username=${DB_USERNAME} \
            --set global.postgresql.auth.password=${DB_PASSWORD} \
            --set global.postgresql.auth.postgresPassword=${DB_SU_PASSWORD} \
            --set global.postgresql.auth.database=${DB_NAME} > rendered/Data.yaml

      - name: Debug secrets
        run: |
          echo "CD_REPO: ${#CD_REPO}"
          echo "CD_PAT length: ${#CD_PAT}"
        env:
          CD_REPO: ${{ secrets.CD_REPO }}
          CD_PAT: ${{ secrets.CD_PAT }}

      - name: Debug Git remote
        run: |
          git remote -v
          git ls-remote https://$CD_PAT@github.com/$CD_REPO.git || echo "::error:: ls-remote failed"

      - name: Upload rendered files
        env:
          CD_PAT: ${{ secrets.CD_PAT }}
          CD_REPO: ${{ secrets.CD_REPO }}
        run: |
          git config --global user.name "CD Pipeline"
          git config --global user.email "cd_pipeline@dayfit.pl"
          git add rendered/
          git diff --cached --quiet || git commit -m "Uploading new CD configuration"
          git push https://$CD_PAT@github.com/$CD_REPO.git HEAD:main
