name: Upload rendered charts into CD repository
on:
  release:
    types:
      - released

jobs:
  update-cd:
    runs-on: ubuntu-22.04
    environment:
      name: CD pipeline
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build helm dependencies
        run: | 
          cd helm/Data
          helm dependency build

      - name: Copy charts
        env:
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_SU_PASSWORD: ${{ secrets.DB_SU_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          mkdir -p charts
          cp helm/ charts/

      - name: Upload charts to ArgoCD repo
        env:
          CD_PAT: ${{ secrets.CD_PAT }}
          CD_REPO: ${{ secrets.CD_REPO }}
        run: |
          cd charts
          git init
          git config user.name "CD Pipeline"
          git config user.email "cd_pipeline@dayfit.pl"
          git remote add origin https://x-access-token:${CD_PAT}@github.com/${CD_REPO}.git
          git add .
          git commit -m "Upload new CD configuration"
          git branch -M main
          git push -f origin main